In [1]:
import pandas as pd
data = pd.read_csv('real_estate_valuation_data_set.csv', index_col=0)
data.shape

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_42096\645160195.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

(414, 7)

In [2]:
data.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

X1: fecha de Ãºltimo movieminto
X2: edad del inmueble
X3: distancia a la estacion de metro mas cercana
X4: Numero de tiendas de conveniencia
X5: corresponde a la latitud en la cordenadas
X6: Corresponde a la longitud en las coordenadas
Y: Variable de respuesta expresando precio por metro cuadrado

In [3]:
data.describe()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
count,414.000000,414.000000,414.000000,414.000000,414.000000,414.000000,414.000000
mean,2013.148971,17.712560,1083.885689,4.094203,24.969030,121.533361,37.980193
std,0.281967,11.392485,1262.109595,2.945562,0.012410,0.015347,13.606488
min,2012.667000,0.000000,23.382840,0.000000,24.932070,121.473530,7.600000
25%,2012.917000,9.025000,289.324800,1.000000,24.963000,121.528085,27.700000
50%,2013.167000,16.100000,492.231300,4.000000,24.971100,121.538630,38.450000
75%,2013.417000,28.150000,1454.279000,6.000000,24.977455,121.543305,46.600000
max,2013.583000,43.800000,6488.021000,10.000000,25.014590,121.566270,117.500000

In [4]:
%pip install geopy
from geopy.geocoders import Nominatim

coordenadas = (24.96903, 121.53336)

#Creao un geolocalizador
geolocalizador = Nominatim(user_agent="mi_aplicacion")

#Obtengo la direcciÃ³n con las coordenadas
ubicacion = geolocalizador.reverse(coordenadas)

#Imprimo la direcciÃ³n
print("DirecciÃ³n encontrada:", ubicacion.address)

Collecting geopyNote: you may need to restart the kernel to use updated packages.

  Obtaining dependency information for geopy from https://files.pythonhosted.org/packages/e5/15/cf2a69ade4b194aa524ac75112d5caac37414b20a3a03e6865dfe0bd1539/geopy-2.4.1-py3-none-any.whl.metadata
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
     ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
     ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
     ---------- ----------------------------- 10.2/40.3 kB ? eta -:--:--
     ------------------- ------------------ 20.5/40.3 kB 217.9 kB/s eta 0:00:01
     ---------------------------- --------- 30.7/40.3 kB 187.9 kB/s eta 0:00:01
     -------------------------------------- 40.3/40.3 kB 192.8 kB/s eta 0:00:00
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   --- ------------------------------------ 10.2/125.4 kB ? eta -:--:--
   ------------------- -------------------- 61.4/125.4 kB 3.4 MB/s eta 0:00:01
   ------------------- -------------------- 61.4/125.4 kB 3.4 MB/s eta 0:00:01
   ------------------- -------------------- 61.4/125.4 kB 3.4 MB/s eta 0:00:01
   ------------------- -------------------- 61.4/125.4 kB 3.4 MB/s eta 0:00:01
   ---------------------------- ---------- 92.2/125.4 kB 350.1 kB/s eta 0:00:01
   -------------------------------------  122.9/125.4 kB 400.9 kB/s eta 0:00:01
   -------------------------------------- 125.4/125.4 kB 410.0 kB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.1

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

DirecciÃ³n encontrada: æ°åºæºªå³å²¸èªè¡è»é, ä¸­è¯é, æ°åºå, å¤§åªæ, æ°åå¸, 231015, èºç£

Respecto al conteo de los datos no hay algo relevante para resaltar pues como tenemos esa tabla de datos de entrada se confirma que es un arreglo rectangular con todos los datos completos.

Comportamiento individual de cada caracterÃ­stica y variable de respuesta.
-Transaction date: ?????????
-House age: El promedio de las casas que se tienen en la base de datos es de unos 17 aÃ±os, lo que indica que no son propiedades muy nuevas, pero como lo indica tambien el mÃ¡ximo una propiedad de 43 aÃ±os tampoco es vieja. Los datos varÃ­an bastante respecto a la media en esta muestra con una desvest de 11,39 aÃ±os.
-Distance to the nearest MRT station: Para las propiedades en cuestion la media de distancia hasta el metro es bastante significativa, podrÃ­a dar indicios que se ubican en zonas lejanas del centro o incluso zonas rurales. Igualmente los datos distan bastante de la media y esto tambien muestra que es un rango bastante amplio en el oscilan las distancias.
-NÃºmero de tiendas de conveniencia: Esta caracterÃ­stica bastante importante para la valuacion tiene en promedio una buena medida, con 4 tiendas de conveniencia en su entorno de media y una desviaciÃ³n de 3 aproximadamente. Como hay propiedades en la muestra que no tienen ni una de estas tiendas cerca tambien hay unas que tienen una ubicacion privilegiada contando con unas 10 tiendas.
-Latitud y Longitud: